# Generated by Django 5.2.3 on 2025-06-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_company_job_salary_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
